### ISSUE TITLE
Polar auxin transport - missing gene products (and reaction) in projections; diagram misdrawn

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/production-issues#1]
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=8858053&PATH=2894885,2744345,2744341
Few issues.
- diagram got messed up on the right side
-  The projections does not recognize anything on the right hand size for PIN protein genes
  e.g. citrus http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=8884629&DIAGRAM=8892891&PATH=8892698,8892697,8892710
  A. thaliana http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=8950633&DIAGRAM=8955775&PATH=8955592,8955591,8955604

A. thaliana should have picked up the homologs of PIN. Can you check in the homology files
rice gene Os01g0643300 has 12 paralogs and orthologs to in A. thaliana i.e. AT1G70940, AT2G01420, AT1G23080.

**Comment by deustp01** [comment]
Fixed the diagram in gk_central. (I don't know how to patch a diagram instance in the slice db.)

**Comment by jaiswalp** [comment]
Thanks Peter. I think for the slice we might have to live with it.

Pankaj

On 3/11/2016 12:14 PM, deustp01 wrote:

> Fixed the diagram in gk_central. (I don't know how to patch a diagram 
> instance in the slice db.)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/PlantReactome/temp-issues/issues/1#issuecomment-195528236.

## 

Pankaj Jaiswal, PhD
Associate Professor
Dept. of Botany and Plant Pathology
2082 Cordley Hall
Oregon State University
Corvallis, OR, 97331
USA

Ph.: +1-541-737-8471
Fax: +1-541-737-3573
email: jaiswalp@oregonstate.edu
Web: http://jaiswallab.cgrb.oregonstate.edu/

**Comment by preecej** [comment]
We could experiment with updating the diagram directly from the curator db to our slice, but I suggest we make that a lower priority and try it if there's time before the release date.

Looking into orthology mapping for genes mentioned.

**Comment by preecej** [comment]
Cannot directly upload the corrected XML (after downloading from gk_central) to local slice. Tried it; XML property not visible, and does not allow merging. We'll have to get it in the next slice.

PIN gene mentioned now present in At projections. Will not appear in citrus projections until inparanoid clusters downloads for OS ids are appended. Will become a moot point when LOC ids are updated before next release.

**Comment by preecej** [comment]
Projection fixed and deployed to Test. Verified and closed:

http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=8951557&DIAGRAM=8957055&ID=8956851&PATH=8956872,8956871,8956884&DTAB=MT

Diagram repaired in central db. Will appear in Release 51.
