### ISSUE TITLE
Content updates needed in Plant reactome

### ISSUE THREAD

**Issue by naithanis** [PlantReactome/production-issues#11]
1. Include Parul Gupta as a curator in Plant Reactome Team
   Link at footer: http://plantreactomedev.oicr.on.ca/?page_id=581

Also see if the people from other groups need update
1. Other Reactome: Reactome is not included
   http://plantreactomedev.oicr.on.ca/?page_id=298
2. Reactome (Table of Contents) needs update (I do not know if it is generated automatically)
   http://plantreactomedev.oicr.on.ca/cgi-bin/toc?DB=test_slice_oryza_sativa_13_ortho_osat_all
   it is actually people info, not table of content: we may change the name. Table of contents should be the summary release table listing species and pathways.
   In the authors section, list current curators first.
   In Reviewer section, add Pankaj and list current members first, Sushma has two IDs 
3. Citing Plant Reactome: needs update: add Gramene 2016 NAR
4. Plant Reactome Downloads: need to update # of species to 62

**Comment by jaiswalp** [comment]
On 3/29/2016 9:26 AM, naithanis wrote:

> Citing Plant Reactome: needs update: add Gramene 2016 NAR

This looks different on live site 
http://plantreactome.gramene.org/?page_id=1418
let me know when to edit

Pankaj

**Comment by jaiswalp** [comment]
On 3/29/2016 9:26 AM, naithanis wrote:
> In the Pathway Browser Bottom right-hand side window : there is 0 data 
> in structure. I think we should have had the molecular formula for the 
> compounds at least.
This is for protein structure I believe. Majority may not have entries 
in PDB. See for example on Reactome 
http://www.reactome.org/PathwayBrowser/#/R-HSA-418346&SEL=R-HSA-419490&PATH=R-HSA-109582&DTAB=ST

@naithanis is also suggesting that we can show structure of simple 
entities if available. proteins is a tough call and may not even have hits.

**Comment by preecej** [comment]
Are you referring to This event does not contain Rhea structures to be shown?

I will check the source code and see if this is a configuration issue. (E.g., not pointing to the correct location to retrieve structure, or sending the wrong data.)

Alternately, molecular compound data is available via the Small Molecule Search <http://plantreactomedev.oicr.on.ca/cgi-bin/small_molecule_search?DB=test_slice_oryza_sativa_13_ortho_osat_all> feature.

- Justin

**Comment by preecej** [comment]
Moving empty Structure tab issue to #12 

As for the content updates, we will handle directly in Wordpress on live site during migration. Previews of more complicated Wordpress content can be prototyped in Test as needed. Everyone (except perhaps Parul) has a Wordpress account on these sites.

The "TOC" is db-driven. We can change the name in the menu and header, but it's not really worth it, IMO. I suggest that @naithanis  work with @deustp01 to merge her two author accounts. Comparing ours to human Reactome's -- http://www.reactome.org/cgi-bin/toc?DB=gk_current -- perhaps we are not marking our releases properly in the db in order for this info to show. @deustp01 ?

**Comment by preecej** [comment]
Re: item 2:

Hi Justin,
I don’t understand how the TOC is generated, so no clue how to repair or revise one.
Sushma actually has three person instances in gk_central, one from co-authorship of a paper, and two associated with edits in the database, one used once and one used several times. I can get everything to point to that last instance. Shall I do that now? (This affects only gk_central, of course – you’d need to make and process another slice to get it to appear on the public-facing web site.)
Peter

Thanks. I’ll ask about the TOC release data on the call tomorrow morning.
No rush on merging Sushma’s accounts. Just do at your leisure and we’ll pick it up in the next release. Thank you.  :)
- Justin Preece

**Comment by preecej** [comment]
@jaiswalp These content pages can be updated at any time to your liking, since none of these corrections are release-specific:
- http://plantreactome.gramene.org/?page_id=581 (add Parul, remove Sheldon)
- http://plantreactome.gramene.org/?page_id=298 (add Reactome, remove Plant Reactome)
- http://plantreactome.gramene.org/?page_id=1418 (add Gramene 2016 NAR)

Thanks!

**Comment by preecej** [comment]
To clarify: updated in Production.

**Comment by preecej** [comment]
Reactome Team page updated.

**Comment by preecej** [comment]
"Other Reactomes" updated.

**Comment by preecej** [comment]
Citation page updated.
