### ISSUE TITLE
How does highlightPathwayDiagram API endpoint work?

### ISSUE THREAD

**Issue by mycrobe** [PlantReactome/production-issues#13]
We would _love_ to integrate Plant Reactome pathways into [Gramene's new search thing](http://search.gramene.org)

I've been trying to get highlightPathwayDiagram to work for me. Take a look at this interactive javascript playground to see how I've approached it.
https://tonicdev.com/mycrobe/reactome-pathway-image

As you can see, no part of the pathway diagram is highlihgted. How do we make that happen?

**Comment by preecej** [comment]
New DiagramJs and WidgetJs implemented, released, and integrated with Gramene. This ticket is  obsolete.
