### ISSUE TITLE
Search doesn't work well for protein/enzyme search

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/production-issues#14]
For protein/enzyme search, search results doesn't show up with correct pathways containing that protein. For example- I searched for Phosphoglycerate kinase using search box and search results are...
http://plantreactome.gramene.org/content/query?q=phosphoglycerate+kinase&species=Oryza+sativa&species=Entries+without+species&cluster=true&page=1 
it shows 6 pathways containing this protein-
http://plantreactome.gramene.org/content/query?q=phosphoglycerate+kinase&species=Oryza+sativa&species=Entries+without+species&types=Pathway&cluster=true
only one of them (Cytosolic glycolysis) contain the searched protein. This protein actually from Calvin cycle which is not showing up here in search results.

**Comment by preecej** [comment]
Those results are due to a wildcard search for phosphoglycerate AND/OR kinase. The other five results are due to the presence of the keyword "kinase" or the keyword "phosphoglycerate".

If you search for "phosphoglycerate AND/OR kinase", you only get the Cytosolic glycolysis pathway result.
