### ISSUE TITLE
Pathway rendering on live plantreactome site not working well

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/production-issues#15]
Ammonia assimilation pathway looks good on reactomedev site
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=1119443&PATH=2894885,2744345,5368291

but not rendering well on plantreactome live site
http://plantreactome.gramene.org/PathwayBrowser/#DIAGRAM=1119443&PATH=2894885,2744345,5368291

and not projected to other species as well, e.g.;
http://plantreactome.gramene.org/PathwayBrowser/#SPECIES=8951557&DIAGRAM=8956902&PATH=8956872,8956871

**Comment by preecej** [comment]
Checked. Seems to be ok now.
