### ISSUE TITLE
Pathways showing up on Plantreactomedev but not on live site

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/production-issues#16]
Inorganic nutrients metabolism showing 5 sub pathways on Plantreactomedev site 
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=5368291&PATH=2894885,2744345 

whereas only 3 are showing up on live site
http://plantreactome.gramene.org/PathwayBrowser/#DIAGRAM=5368291&PATH=2894885,2744345

Cyanate degradation and Nitrate assimilation pathways are missing on live site

**Comment by preecej** [comment]
They are now present on live site. Fixed.
