### ISSUE TITLE
Analysis Tools: File upload not working on new Test server (.88)

### ISSUE THREAD

**Issue by preecej** [PlantReactome/production-issues#19]
Testing the file upload feature on Analysis Tools; it's not working on new Test server (.88). 
[glycine_max_E-MTAB-4352.txt](https://github.com/PlantReactome/temp-issues/files/643347/glycine_max_E-MTAB-4352.txt)
Current test and live servers work with attached file.

New test server throws alert error: "Error processing the result. Please get in touch with our help desk at help@reactome.org".

Looks like file permissions: Error: 400
 Message: Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /etc/apache-tomcat-7.0.61/work/Catalina/localhost/AnalysisService/upload_164adf80_b997_4bed_8af2_77ea86b148ec_00000008.tmp (Permission denied)
Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /etc/apache-tomcat-7.0.61/work/Catalina/localhost/AnalysisService/upload_164adf80_b997_4bed_8af2_77ea86b148ec_00000008.tmp (Permission denied)

**Comment by elserj** [comment]
/etc/apache-tomcat-7.0.61/work/Catalina/localhost/AnalysisService was owned by root.  Changed to tomcat7:tomcat7 with chown tomcat7:tomcat7 (note not recursive).  Seems to work fine now.

**Comment by preecej** [comment]
Verified with soybean test data.
