### ISSUE TITLE
CGI-generated pages not loading on future Prod VM

### ISSUE THREAD

**Issue by preecej** [PlantReactome/production-issues#20]
Probably permissions issue for CGI scripts...

Downloads: http://206.108.120.64/download/ (no header/footer)
TOC: http://206.108.120.64/cgi-bin/toc?DB=test_slice_oryza_sativa_14_ortho_osat_all
Data Schema: http://206.108.120.64/cgi-bin/classbrowser?DB=test_slice_oryza_sativa_14_ortho_osat_all
Small molecule search: http://206.108.120.64/cgi-bin/small_molecule_search?DB=test_slice_oryza_sativa_14_ortho_osat_all

**Comment by elserj** [comment]
Was actually 2 issues.  First, all perl scripts in cgi-bin had /usr/local/bin/perl in the shebang, which didn't exist. Created symlink to /usr/bin/perl to fix this.

Second, some perl modules were missing, most notably gd and bioperl.  Installed gd with apt-get and bioperl via cpan.  Also XML::Parser, Data::Dumper and Inline.

Think that was it, might have been a few other modules, but that is what I can see that I installed.

**Comment by preecej** [comment]
Confirmed. All four CGI-based features now work.
