### ISSUE TITLE
create simplified documentation for RESTful APIs, widgets, and bulk downloads

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/production-issues#23]
From Ethy Cannon

I know Reactome has a REST API, but in attempting to make some simple queries, appears either to not be functional at Plant Reactome, or my queries are incorrect.

**Comment by preecej** [comment]
need to create a more simplified API "how-to" specifically for Plant Reactome, using Reactome's existing documents for the original RESTful API, ContentService, AnalysisService, bulk downloads, and graphical widgets

**Comment by preecej** [comment]
Merged into the Joomla enhancement.
