### ISSUE TITLE
ContentService - no top level pathways for taxonomy id 39947

### ISSUE THREAD

**Issue by ajo2995** [PlantReactome/production-issues#29]
This endpoint returns the top level pathways for a species given the taxonomy id.

The Arabidopsis thaliana taxonomy id works fine:
http://plantreactomedev.oicr.on.ca/ContentService/data/pathways/top/3702
`[{"dbId":9085216,"displayName":"Circadian rhythm","stId":"R-ATH-8933811","isInDisease":false,"isInferred":true,"name":["Circadian rhythm"],"speciesName":"Arabidopsis thaliana","hasDiagram":true,"schemaClass":"TopLevelPathway","className":"TopLevelPathway"},{"dbId":9085218,"displayName":"Inflorescence development","stId":"R-ATH-8934088","isInDisease":false,"isInferred":true,"name":["Inflorescence development"],"speciesName":"Arabidopsis thaliana","hasDiagram":true,"schemaClass":"TopLevelPathway","className":"TopLevelPathway"},{"dbId":9085018,"displayName":"Metabolism and regulation","stId":"R-ATH-2744345","isInDisease":false,"isInferred":true,"name":["Metabolism and regulation"],"speciesName":"Arabidopsis thaliana","hasDiagram":true,"schemaClass":"TopLevelPathway","className":"TopLevelPathway"},{"dbId":9085215,"displayName":"Response to stress","stId":"R-ATH-8932729","isInDisease":false,"isInferred":true,"name":["Response to stress"],"speciesName":"Arabidopsis thaliana","hasDiagram":true,"schemaClass":"TopLevelPathway","className":"TopLevelPathway"}]`

but not Oryza sativa japonica:
http://plantreactomedev.oicr.on.ca/ContentService/data/pathways/top/39947
`{"code":404,"reason":"NOT_FOUND","url":"http://localhost:8080/ContentService/data/pathways/top/39947","messages":["No TopLevelPathways were found for species: 39947"]}`

**Comment by preecej** [comment]
We use "Oryza sativa" (NCBI:4530) as our reference taxon. There are artifact "subsp. japonica" entries in the PR db, but all visible rice pathways, reactions, entities, etc. are associated with 4530.

i.e. http://plantreactomedev.oicr.on.ca/ContentService/data/pathways/top/4530
