### ISSUE TITLE
cardiolipin pathway not appearing in projections

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/production-issues#3]
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=1119260&PATH=2894885,2744345,3906998
Reaction- phosphatidylglycerol phosphate ---> L-1-phosphatidylglycerol is catalyzed by phosphatidylglycerophosphatase in Oryza sativa.

This reaction (phosphatidylglycerol phosphate ---> L-1-phosphatidylglycerol) is not showing up in either Zea mays (even, O. sativa ortholog was selected from Z. mays) or any other projections.
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=9033573&DIAGRAM=9039349&PATH=9039205,9039204,9039207

**Comment by preecej** [comment]
The gene product acting as the catalyst for this reaction is Os01g0796500 (UniProt:Q0JIJ8). Expanded Ensemble mapping to Os ids means I expect it to show up in many places inc. maize:

13/osat_zmay_mapping.txt:Q0JIJ8 Ensembl:GRMZM2G349603
...
13/osat_alyr_mapping.txt:Q0JIJ8 Ensembl:fgenesh2_kg.5__2333__AT3G58830.1
13/osat_atau_mapping.txt:Q0JIJ8 Ensembl:F775_32548
13/osat_atha_mapping.txt:Q0JIJ8 Ensembl:AT3G58830
13/osat_atri_mapping.txt:Q0JIJ8 Ensembl:AMTR_s00032p00201850
13/osat_bdis_mapping.txt:Q0JIJ8 Ensembl:BRADI2G52356
13/osat_bole_mapping.txt:Q0JIJ8 Ensembl:Bo6g076110
13/osat_brap_mapping.txt:Q0JIJ8 Ensembl:Bra003358
13/osat_crei_mapping.txt:Q0JIJ8 Ensembl:CHLREDRAFT_189394
13/osat_gmax_mapping.txt:Q0JIJ8 Ensembl:GLYMA04G29890
13/osat_hvul_mapping.txt:Q0JIJ8 Ensembl:MLOC_64653
13/osat_lper_mapping.txt:Q0JIJ8 Ensembl:LPERR01G29230
13/osat_macu_mapping.txt:Q0JIJ8 Ensembl:GSMUA_Achr9G25050_001
13/osat_mtru_mapping.txt:Q0JIJ8 Ensembl:MTR_3g079530 Ensembl:MTR_1g046360
13/osat_obra_mapping.txt:Q0JIJ8 Ensembl:OB01G42690
13/osat_ogla_mapping.txt:Q0JIJ8 Ensembl:ORGLA01G0277800
13/osat_oglu_mapping.txt:Q0JIJ8 Ensembl:OGLUM01G38070
13/osat_oluc_mapping.txt:Q0JIJ8 Ensembl:OSTLU_5256
13/osat_omer_mapping.txt:Q0JIJ8 Ensembl:OMERI01G30690
13/osat_oniv_mapping.txt:Q0JIJ8 Ensembl:ONIVA01G38640
13/osat_opun_mapping.txt:Q0JIJ8 Ensembl:OPUNC01G32890
13/osat_oruf_mapping.txt:Q0JIJ8 Ensembl:ORUFI01G37100
13/osat_osai_mapping.txt:Q0JIJ8 Ensembl:BGIOSGA000655
13/osat_ppat_mapping.txt:Q0JIJ8 Ensembl:PP1S13_181V6
13/osat_ptri_mapping.txt:Q0JIJ8 Ensembl:POPTR_0005s22290 Ensembl:POPTR_0002s06140
13/osat_sbic_mapping.txt:Q0JIJ8 Ensembl:Sb03g037050
13/osat_sita_mapping.txt:Q0JIJ8 Ensembl:Si002521m.g
13/osat_slyc_mapping.txt:Q0JIJ8 Ensembl:Solyc07g055980.2 Ensembl:Solyc12g011020.1
13/osat_smoe_mapping.txt:Q0JIJ8 Ensembl:SELMODRAFT_75149 Ensembl:SELMODRAFT_87061
13/osat_stub_mapping.txt:Q0JIJ8 Ensembl:PGSC0003DMG400007795 Ensembl:PGSC0003DMG400017343
13/osat_taes_mapping.txt:Q0JIJ8 Ensembl:TRAES3BF034800060CFD_g
13/osat_tcac_mapping.txt:Q0JIJ8 Ensembl:TCM_001858
13/osat_tura_mapping.txt:Q0JIJ8 Ensembl:TRIUR3_17684
13/osat_vvin_mapping.txt:Q0JIJ8 Ensembl:VIT_12s0142g00220

**Comment by preecej** [comment]
I will confirm in test before closing this issue.

**Comment by preecej** [comment]
Now present. Deployed in Test: please verify and close.

http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=9039406&DIAGRAM=9045592&ID=9039925&PATH=9045546,9045545,9045548&DTAB=MT
