### ISSUE TITLE
pathway diagram corrections for 56b

### ISSUE THREAD

**Issue by guptapa** [PlantReactome/production-issues#33]
Subpathways are missing-
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#/R-OSA-9030654&PATH=R-OSA-9030769,R-OSA-9031670&DTAB=EX

Subpathway (lateral root development) is missing-
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#/R-OSA-9031225&PATH=R-OSA-8932729&DTAB=EX

Subpathways are missing-
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#/R-OSA-9030908&SEL=R-OSA-9030828&PATH=R-OSA-8932729,R-OSA-9030860&DTAB=EX

**Comment by preecej** [comment]
Working to adjust the diagrams accordingly.

**Comment by preecej** [comment]
Done.
