### ISSUE TITLE
ABA Biosynthesis - missing projections

### ISSUE THREAD

**Issue by preecej** [PlantReactome/production-issues#38]
The ABA biosynthesis pathway is no longer showing projections.

Investigating whether there is a problem with PR orthology data pre-processing, or possible issue with multiple references to the pathway in the hierarchy.

**Comment by preecej** [comment]
Observation: ABA Biosynthesis and its child pathways (Abscisic acid biosynthesis, Abscisic acid (ABA) mediated signaling) are not projecting at all. Still investigating whether this is an event-level or a gene product-level issue. My gut says event-level, b/c an entire sets of pathways is being left out of orthoinference.

Currently checking logs from last orthoinference and also orthopair files. Testing with latest orthoinference, as well.

**Comment by deustp01** [comment]
Justin,
Together with the message from you, I just got this one from Parul.
I just noticed one BB event- "Expression of AUX1” is missing from the diagram
http://curator.reactome.org/PathwayBrowser/#/R-OSA-9608575&PATH=R-OSA-2894885,R-OSA-9030769,R-OSA-9031669<https://urldefense.proofpoint.com/v2/url?u=http-3A__curator.reactome.org_PathwayBrowser_-23_R-2DOSA-2D9608575-26PATH-3DR-2DOSA-2D2894885-2CR-2DOSA-2D9030769-2CR-2DOSA-2D9031669&d=DwMFaQ&c=j5oPpO0eBH1iio48DtsedeElZfc04rx3ExJHeIIZuCs&r=F4m-1K6kLSvIj0HPW9YAIDzb_mrtWnFjzjfDOCMSHK0&m=E0-_Xy9I2M4zNUYkk7QVI1_NKVgqJnmQz_rTP2XYPTQ&s=vLFctbZBx4IaEG1K6OpMWJnedfbP1Ir6ktCLKThlATo&e=>
I cloned the existing event and added negative regulators and a literature reference which is different from the exiting one. In this diagram AUX1 is not associated with any event so I assume It would not show up in diagram when this pathway will be sliced for upcoming release. Can you please fix it? cloned BB reaction is already in rtpj I sent to you. I wondered whether it is good strategy to clone a reaction if there is different regulators associated in a particular pathway. Hope it wouldn’t break or create a mess with anything in gk central.
I don’t understand exactly what the current problem is and how her change is intended to fix it. And today is your slice-freeze deadline, right?
Could you and she take another stab at figuring out what is needed, and let me know? Though there’s not likely to be time to do anything more substantial this week.
Sorry
Peter

**Comment by preecej** [comment]
My ABA note is not intended to create urgency for fixes. It's just something I'm trying to address when there is time. Don't even know if a fix is required at the event level, or the ortho level. Don't worry about it right now.

As for Parul's request: @guptapa Is this a critical fix, or something that we can log as a separate issue and address when there is less pressure? It seems like there may be complexity, and last-minute changes can be higher-risk.

**Comment by preecej** [comment]
New orthoinference process has automagically addressed this issue, at least in the db. "Abscisic acid biosynthesis", "Abscisic acid (ABA) mediated signaling", and parent pathway "ABA biosynthesis and mediated signaling" all appearing and projecting. Will wait to close until verified that diagrams have propagated all the way through graph conversion and JSON diagram generation.

**Comment by preecej** [comment]
Diagrams for projections are ok.
