### ISSUE TITLE
Expression overlay does not work for all projected species

### ISSUE THREAD

**Issue by preecej** [PlantReactome/production-issues#4]
**Expression overlay**
- Displays gradient coloring for many more Ensembl species...seems to be hit and miss. Could be an gene product name format issue - isoforms with suffixes don't work
- Displays gradient coloring for other species on container pathways only (but analysis data is still available at the bottom)
- Non-Ensembl species are not showing expression overlay results. Could be an id mapping issue. 

So, some expression gradient coloring issues remain for non-reference species.

**Comment by naithanis** [comment]
ok

**Comment by preecej** [comment]
This should be fixed now with the Reactome 3.3 release, but I want to test it extensively with expression data for multiple Ensembl and Inparanoid species.
