### ISSUE TITLE
DiagramJs example fails to load - likely CORS issue

### ISSUE THREAD

**Issue by preecej** [PlantReactome/production-issues#41]
http://plantreactome.gramene.org/index.php?option=com_content&view=article&id=58&Itemid=306&lang=en

Cross-protocol request not allowed. Need to reconfigure request to use https.

diagram-0.js:4783 Mixed Content: The page at 'https://plantreactomedev.gramene.org/index.php?option=com_content&view=article&id=58&Itemid=306&lang=en' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://plantreactome.gramene.org/ContentService/interactors/psicquic/resources'. This request has been blocked; the content must be served over HTTPS.

Also true here: 
https://plantreactome.gramene.org/DiagramJs/

**Comment by elserj** [comment]
Fixed by changing the "proxyPrefix" link in the "onReactomeDiagramReady" function on the joomla "Diagram JS" page to include the https.

Also changed the links to /DiagramJs to the fixed page.

Done on all 3 sites.

@preecej, I don't have permissions to close the ticket.
