### ISSUE TITLE
Ref species O. sativa on tops of the species list

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/production-issues#46]
I see that on the live site browser, O. sativa reference is not listed on the top of the dropdown species list. It is currently alphabetically sorted.

**Comment by preecej** [comment]
Correct on dev and mirror sites. Production site is missing relevant version of the Pathway Browser with custom PR code change to place O. sativa on top of list.

Currrent PathwayBrowser software merging should include the relevant change with next release.

**Comment by preecej** [comment]
@elserj Let's try moving the Test PathwayBrowser WAR file to local Dev (cord3084), change config paths as needed, and see if that works without breaking other browsing features (should be ok). After a positive test, that will confirm that our current PathwayBrowser code base, soon to be merged, will include the relevant code when moved out for the next release.

**Comment by preecej** [comment]
O. sativa is back on the top of the list.
