### ISSUE TITLE
How to download BioPAX format data.

### ISSUE THREAD

**Issue by yayamamo** [PlantReactome/production-issues#49]
Hi, while I'm not sure whether here is a right place to ask or not, I'm wondering if there is a dump file of PlantReadtome in the BioPAX format. As described at the following "Downloads" page, I hope you kindly provide it.

https://plantreactome.gramene.org/index.php?option=com_content&view=article&id=18&Itemid=242&lang=en

Thanks.

**Comment by deustp01** [comment]
It's available on our download page:
[https://plantreactome.gramene.org/download/current](https://urldefense.com/v3/__https://plantreactome.gramene.org/download/current/biopax3.zip__;!!MXfaZl3l!Z_n7EO_Dgj1HeFyv_YR2u-kVG6ENzyIu0Zlh6ZVTFoSdisqQt3gzc2dgCToe-hUNgL0xJABiA5MHpWnV9u_ggHT4rsZxgVebNmQ4K9X4$)
and the direct link to the biopax zip archive.
[https://plantreactome.gramene.org/download/current/biopax3.zip](https://urldefense.com/v3/__https://plantreactome.gramene.org/download/current/biopax3.zip__;!!MXfaZl3l!Z_n7EO_Dgj1HeFyv_YR2u-kVG6ENzyIu0Zlh6ZVTFoSdisqQt3gzc2dgCToe-hUNgL0xJABiA5MHpWnV9u_ggHT4rsZxgVebNmQ4K9X4$)

**Comment by yayamamo** [comment]
Thank you for your response. I'd be glad if you would put this link at the Download page.

**Comment by elserj** [comment]
Added to joomla download page on both dev and live.
