### ISSUE TITLE
Atlas expression data

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/production-issues#6]
From Sushma:

1: The expression data is being projected from Human/mouse  in the following pathways

Plant Pathways (projections from human)
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=2894885&DTAB=EX

Cellular process (projection from human)
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=2894886&PATH=2894885&DTAB=EX

ABA Biosynthesis and mediated signaling (projection is from human)
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=3899368&PATH=2894885,2744345,2744341&DTAB=EX

Abscisic  acid mediated signaling
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=3899368&ID=3899351&PATH=2894885,2744345,2744341&DTAB=EX

Ethylene biosynthesis and signaling (projection is from mouse)
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=5225808&PATH=2894885,2744345,2744341&DTAB=EX

Amine and polyamine biosynthesis (projection is from mouse)
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=5096066&PATH=2894885,2744345&DTAB=EX

**Comment by jaiswalp** [comment]
Confirming, the same occurs for top level bin pathways on live site:
- plant pathways http://plantreactome.gramene.org/PathwayBrowser/#DIAGRAM=2894885&DTAB=EX
- cellular processes http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=2894886&PATH=2894885&DTAB=EX

Works for metabolic pathways 
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=2744345&PATH=2894885&DTAB=EX

**Comment by jaiswalp** [comment]
I believe some of the top level expression views are not working especially for cellular pathways. because we do not generate the indexes for ATLAS configuration. (Justin please confirm). But even if we ignore 'cellular processes' all the 'metabolic and regulatory' ones should show up at the top 'plant pathways'

**Comment by preecej** [comment]
That's a good guess: no indices for container pathways. Thanks for all the detail. I am looking into it.

**Comment by jaiswalp** [comment]
confirming:  on live site that goes to human
ABA http://plantreactome.gramene.org/PathwayBrowser/#DIAGRAM=3899368&PATH=2894885,2744345,2744341&DTAB=EX
Ethylene http://plantreactome.gramene.org/PathwayBrowser/#DIAGRAM=5225808&PATH=2894885,2744345,2744341&DTAB=EX

**Comment by jaiswalp** [comment]
Top level Salicylic acid signaling : http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=6788019&PATH=2894885,2744345,2744341 does not show expression, but expression is visible for individual reactions http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=6788019&ID=6788032&PATH=2894885,2744345,2744341&DTAB=EX
or complex http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=6788019&ID=6788138&PATH=2894885,2744345,2744341&DTAB=EX

**Comment by guptapa** [comment]
Citrulline-nitric oxide cycle 
No expression dat showing up
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=5633340&PATH=2894885,2744345,2744343&DTAB=EX

**Comment by guptapa** [comment]
amino acid catabolism showing-
no baseline experiment for species Rattus 
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=5655124&PATH=2894885,2744345,2744343&DTAB=EX
but in sub pathways under this category is all visible

**Comment by guptapa** [comment]
No expression data in Beta-alanine biosynthesis I
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=1119567&PATH=2894885,2744345,2744343,5655122&DTAB=EX

**Comment by jaiswalp** [comment]
Same issue with citrulline. not for pathway but shows up for reaction http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=5633340&ID=1120995&PATH=2894885,2744345,2744343&DTAB=EX

**Comment by preecej** [comment]
Ok, ok. :)   I've got enough examples to work with. Thank you.

**Comment by preecej** [comment]
The pattern is unclear, and the data for all of these examples appears to be present in the previous release (as well as the current). It seems random whether a particular pathway chooses to display a mouse, human, or rice anatogram, although there is a preponderence of container pathways in the mix.

I will ask Robert.

**Comment by preecej** [comment]
Please, could you specify a species in your REST call? E.g.:
http://www.ebi.ac.uk/gxa/widgets/heatmap/referenceExperiment?geneQuery=5225808&species=oryza+sativa

If no species is provided a search is done across all species and returns the one which we consider is the most relevant.

Let us know if this works for you and don’t hesitate to get in touch with us if you run into any other problems.

Kind regards,

Alfonso

**Comment by preecej** [comment]
working on species specification in Atlas requests....

**Comment by preecej** [comment]
Even without species specification in widget call, the new ATLAS data load of latest Plant Reactome release has fixed the issue. All links provided above now return rice examples. No human or mouse anatograms appear.
- 16 of the above 18 pathway examples have been fixed by providing new data associations.
- For two pathways (salicylic acid signaling & Beta-alanine biosynthesis I), no expression data is available at the pathway level, although it does appear at the reaction level for salicylic acid signaling. This is likely a separate issue.
